# Generated by Django 6.0.4 on 2026-04-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0052_alter_director_movies"),
        ("users", "0014_alter_customlist_movies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="movies",
            field=models.ManyToManyField(blank=True, to="movies.movie"),
        ),
    ]
