# Generated by Django 6.0.4 on 2026-04-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0052_alter_director_movies"),
        ("users", "0013_customlist_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customlist",
            name="movies",
            field=models.ManyToManyField(blank=True, to="movies.movie"),
        ),
    ]
