# Generated by Django 6.0.4 on 2026-04-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0051_review_has_spoilers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="movies",
            field=models.ManyToManyField(
                blank=True, related_name="directors", to="movies.movie"
            ),
        ),
    ]
